"""empty message

Revision ID: 0d1f7baa5577
Revises: 82215018fede
Create Date: 2020-07-15 16:46:10.467190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d1f7baa5577'
down_revision = '82215018fede'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guests', sa.Column('access_code', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'guests', ['access_code'])
    op.create_unique_constraint(None, 'guests', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'guests', type_='unique')
    op.drop_constraint(None, 'guests', type_='unique')
    op.drop_column('guests', 'access_code')
    # ### end Alembic commands ###
