"""empty message

Revision ID: 73139767c07c
Revises: 7be82ff0099b
Create Date: 2021-09-02 21:42:39.601698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73139767c07c'
down_revision = '7be82ff0099b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guests', sa.Column('dinner_preferences', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guests', 'dinner_preferences')
    # ### end Alembic commands ###
