"""empty message

Revision ID: 73b4e8b44f15
Revises: 0d1f7baa5577
Create Date: 2020-07-26 12:56:50.212533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73b4e8b44f15'
down_revision = '0d1f7baa5577'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guests', sa.Column('plus_one', sa.Boolean(), nullable=True))
    op.add_column('guests', sa.Column('plus_one_allowed', sa.Boolean(), nullable=True))
    op.add_column('guests', sa.Column('plus_one_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guests', 'plus_one_name')
    op.drop_column('guests', 'plus_one_allowed')
    op.drop_column('guests', 'plus_one')
    # ### end Alembic commands ###
