"""empty message

Revision ID: 7be82ff0099b
Revises: a7cc718f60f5
Create Date: 2020-08-14 08:52:00.009346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7be82ff0099b'
down_revision = 'a7cc718f60f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guests', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guests', 'notes')
    # ### end Alembic commands ###
