"""empty message

Revision ID: 98b03ed0b89f
Revises: 73b4e8b44f15
Create Date: 2020-08-06 09:17:18.650666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98b03ed0b89f'
down_revision = '73b4e8b44f15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guests', sa.Column('replied', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guests', 'replied')
    # ### end Alembic commands ###
