"""empty message

Revision ID: a7cc718f60f5
Revises: c73063fc549b
Create Date: 2020-08-13 08:57:39.824116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7cc718f60f5'
down_revision = 'c73063fc549b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guests', sa.Column('does_not_attends', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guests', 'does_not_attends')
    # ### end Alembic commands ###
