"""empty message

Revision ID: c73063fc549b
Revises: 98b03ed0b89f
Create Date: 2020-08-13 08:51:13.359610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c73063fc549b'
down_revision = '98b03ed0b89f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guests', sa.Column('invited_to', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guests', 'invited_to')
    # ### end Alembic commands ###
